<?php
/**
 *
 * @var $this \Cubex\View\Layout
 *
 * This is your default layout file, variables in this file act as placeholders for named nested views
 *
 */
?>
<div id="sf-wrap">
  <header>
    <div class="container">
      <div class="row">
        <div class="span4">
          <div class="logo">
            <a href="/">
              <img src="<?php echo $this->imgUrl("/cubex-logo.png"); ?>" alt="Cubex Logo" />
            </a>
          </div>
        </div>
        <div class="span8">
          <nav class="main pull-right">
            <ul class="inline nav strtoupper">
              <?php echo $this->yield("mainNav", false); ?>
            </ul>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="span12">
          <h2 class="text-center">Simpler, faster and less of it.</h2>
        </div>
      </div>
      <div class="row">
        <div class="span12">
          <nav class="cubes">
            <ul class="inline nav strtoupper text-center">
              <?php echo $this->yield("cubesNav", false); ?>
            </ul>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="span12">
          <div class="download text-center">
            <a href="#" class="btn btn-large btn-xlarge btn-warning strtoupper">Download Cubex</a>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div id="body">
    <div class="container">
      <div class="row">
        <div class="span12">
          <?php echo $this->yield("content", "main-content"); ?>
        </div>
      </div>
    </div>
  </div>

  <div id="sf-push"></div>

</div>


<footer>
  <div class="container">
    <div class="row">
      <div class="span6 offset3">
        <a href="#">&copy; Sticky Footer</a> I'm a sticky footer.
      </div>
    </div>
  </div>
</footer>
