<?php
/**
 *
 * @var $this \Cubex\View\Layout
 *
 * This is your default layout file, variables in this file act as placeholders for named nested views
 *
 */
?>
<div id="sf-wrap">
  <header>
    <div class="container">
      <div class="row">
        <div class="span3">
          <div class="logo">
            <a href="/">
              <img src="<?php echo $this->imgUrl("/cubex-logo.png"); ?>"
                   alt="Cubex Logo"/>
            </a>
          </div>
        </div>
        <div class="span9">
          <nav class="main pull-right">
            <ul class="inline nav strtoupper">
              <?php echo $this->renderNest("mainNav", false); ?>
            </ul>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="span12">
          <h2 class="text-center"><?php
            echo $this->getStr("caption", "The Creativity Framework");
            ?></h2>
        </div>
      </div>
      <?php echo $this->renderNest("cubesNav", false); ?>
    </div>
  </header>

  <div id="body">
    <div class="container">
      <div class="row">
        <div class="span12">
          <?php echo $this->renderNest("content", "main-content"); ?>
        </div>
      </div>
    </div>
  </div>

  <div id="sf-push"></div>

</div>


<footer>
  <div class="container">
    <div class="row">
      <div class="offset2 span2">
        <strong>Resources</strong><br/>
        <a href="http://www.github.com/qbex/Cubex">Source on GitHub</a><br/>
        <a href="irc://chat.freenode.net/cubex">IRC Channel</a><br/>
        <a href="http://phabricator.cubex.io/maniphest/task/create/">
          Report Bugs</a><br/>
        <a href="/licence">Licence Information</a>
      </div>
      <div class="span2">
        <strong>Documentation</strong><br/>
        <a href="/docs">Cubex Docs</a><br/>
        <a href="http://api.cubex.io">Cubex API Docs</a><br/>
      </div>
      <div class="span2">
        <strong>Source Groups</strong><br/>
        <a href="https://github.com/qbex">Qbex on GitHub</a><br/>
        <a href="https://github.com/qubes">Qubes on GitHub</a><br/>
        <a href="https://github.com/bundl">Bundls on GitHub</a><br/>
        <a href="https://github.com/themed">Themed on GitHub</a><br/>
      </div>
      <div class="span2">
        <strong>Participate</strong><br/>
        <a href="http://blog.cubex.io">Cubex Blog</a><br/>
        <a href="https://twitter.com/cubexio">Cubex on Twitter</a><br/>
        <a href="http://phabricator.cubex.io/maniphest/task/create/">
          Request Features</a>
      </div>
    </div>
    <div class="row">
      <div class="offset2 span8 text-center">
        <hr/>
        Copyright (c) 2012-<?php echo date("Y"); ?>,
        Just Develop It Ltd.
        All Rights Reserved
      </div>
    </div>
  </div>
</footer>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(
  ['_setAccount', 'UA-38891222-1']
  );
  _gaq.push(
  ['_trackPageview']
  );

  (function ()
  {
    var ga = document.createElement(
    'script'
    );
    ga.type = 'text/javascript';
    ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName(
    'script'
    )[0];
    s.parentNode.insertBefore(
    ga, s
    );
  })(
  );

</script>
