<?php
/**
 * @author: brooke.bryan
 *        Application: Www
 */
?>

<br/>
<div class="row-fluid">
  <div class="offset2 span8">

    <h3>The PHP Framework</h3>

    <p>Cubex is a new PHP framework built around performance,
       ease of use and scalability. Cutting down the amount of code you need
       to write to produce magic every day.</p>

    <h3>The Tools</h3>

    <p>Alongside Cubex as a framework, there are many tools in open development
       which are built to improve the productivity of your team.</p>

    <h4>Sidekick</h4>

    <p>Sidekick is a great companion for any Cubex project, managing your
       projects, configurations, distributed tasks, build &amp; testing
       processes.</p>

    <h4>Cassie</h4>

    <p>Cassie allows you to manage your cassandra clusters, and get an insight
       into your data.</p>

    <h3>The Bundles</h3>

    <p>Bundles plugin to your project, and work through events to improve your
       project. From a simple SQL debugger, to a cassandra based logging system
       with its own toolkit.</p>


    <h3>The Qubes</h3>

    <p>Qubes are a set of extendable tools, giving you a great foundation to
       build upon. These qubes go from a simple bootstrap helper, to a complete
       event based reporting system.</p>

  </div>
</div>
