<?php
/**
 * @author: brooke.bryan
 *        Application: Www
 */
?>
<br/>
<div class="row-fluid">
  <div class="span7">

    <h3>Why use Cubex?</h3>

    <p>Cubex is a PHP framework focused on making the development process simple
       for any size project you work on. If you are building a small brochure
       site or a highly distributed service, Cubex is built to simplify
       everything.</p>

    <h3>Performance</h3>

    <p>Cubex is focused on optimising the speed of every request to ensure your
       code operates as fast as possible.</p>

    <p>Many features have been made integrated into the core to focus on
       reducing your servers load, from caching every static resource through a
       cache server, and on the clients machine, to caching specific parts of
       your pages with ESIs.</p>

    <h3>CLI Tools</h3>

    <p>With our advanced set of CLI tools and helpers, you can quickly build up
       a set of development tools.</p>

    <h3>Data Mappers</h3>

    <p>Data Mappers within Cubex make up the foundations for many data handling
       objects, from form to database objects. This common interface allows you
       to easily switch between various object types without having to re-learn
       the api.</p>

    <h3>View Models</h3>

    <p>We believe that your views should be structured, and you shouldn't be
       building your views on variables that may or may not exist. Because of
       this, ViewModels allow you to extract any view logic away from your
       template, and your controller, to bring a lot more structure to your
       frontend development.</p>

  </div>


  <div class="span5">

    <h4>Phabricator</h4>
    <a href="http://phabricator.cubex.io">Phabricator for Cubex</a><br/>
    <a href="http://phabricator.cubex.io/maniphest/task/create/">Request Feature
                                                                 | Report
                                                                 Bug</a><br/>

    <h4>IRC</h4>
    <a href="irc://chat.freenode.net/cubex">#cubex on FreeNode</a>

    <h4>Project Activity</h4>
    <iframe src="http://phabricator.cubex.io/feed/public/" frameborder="0"
            style="border: 0; width: 100%; height:600px;">
    </iframe>

  </div>

</div>
<br/>
