<?php
/**
 *
 * @var $this \Cubex\View\Layout
 *
 * This is your default layout file, variables in this file act as placeholders for named nested views
 *
 */
?>
<div id="sf-wrap">
  <header>
    <div class="container">
      <div class="row">
        <div class="span3">
          <div class="logo">
            <a href="/">
              <img src="<?php echo $this->imgUrl("/cubex-logo.png"); ?>" alt="Cubex Logo" />
            </a>
          </div>
        </div>
        <div class="span9">
          <nav class="main pull-right">
            <ul class="inline nav strtoupper">
              <?php echo $this->renderNest("mainNav", false); ?>
            </ul>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="span12">
          <h2 class="text-center">Cubex Documentation</h2>
        </div>
      </div>
      <div class="row">
        <div class="span12">
          <nav class="cubes">
            <ul class="inline nav strtoupper text-center">
              <?php echo $this->renderNest("cubesNav", false); ?>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>

  <div id="body">
    <div class="container">
      <div class="row">
        <div class="span12">
          <?php echo $this->renderNest("content", "main-content"); ?>
        </div>
      </div>
    </div>
  </div>

  <div id="sf-push"></div>

</div>


<footer>
  <div class="container">
    <div class="row">
      <div class="span10 offset1">
        &copy; 2012-<?php echo date("Y"); ?> Just Develop It Ltd
      </div>
    </div>
  </div>
</footer>
